---
title: "miR532_BMT_peripheralblood"
author: "Patrick Lac"
date: "April 12, 2020"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r library, message = F}
library(tidyverse)
library(dplyr)
library(ggplot2)
```

Let's begin by importing our data:

``` {r import.data}
metadata <- read.csv("F:/Git/PLac Analyses/miR-532 project/miR532_BMT/Data/200412_MetaData.csv")
JL_data <- read.csv("F:/Git/PLac Analyses/miR-532 project/miR532_BMT/Data/200412_JL_Data.csv")
MB_data <- read.csv("F:/Git/PLac Analyses/miR-532 project/miR532_BMT/Data/200412_MB_Data.csv")
PL_data <- read.csv("F:/Git/PLac Analyses/miR-532 project/miR532_BMT/Data/200412_PL_Data.csv")
```

Next lets attach the different peripheral blood data together:
``` {r combine.data}
Total_PB_data <- rbind(JL_data, MB_data, PL_data)
head(Total_PB_data)
```

We will make a copy of the total data for manipulation:
``` {r data.copy}
Data.copy <- Total_PB_data
```
What are the dimensions of our data?
```{r dim.data}
dim(Data.copy)
```

Next we will filter for CBC data at 5 weeks post-transplant
``` {r filter.5weeks}
Week5 <- subset(Data.copy, Weeks.post.transplant == 5)
```

Let's check the dimensions of our subsetted data:
```{r dim.week5}
dim(Week5)
```

Let's make a dot plot for WBC count:
``` {r WBC}
WBC <- ggplot(Week5, aes(x=Treatment, y=WBC)) +
  stat_summary(fun.data=mean_sdl, fun.args=list(mult=1), binwidth = 0.1, geom="errorbar", color="red", size=1.2, width=0.1) +
  stat_summary(fun.y=mean, geom="crossbar", color="red", size=0.6, width=0.2) +
  geom_dotplot(binaxis="y", binwidth = 0.1, stackdir="center", stackratio=3, dotsize=3) + 
  ylim(0, 12) +
  labs(title = "WBC", x = "Treatment", y = "WBC (10"^"3"*"/"~mu~"L)") +
  theme(plot.title = element_text(hjust=0.5), text=element_text(size=18))

WBC
```
